package io.risotto.exception;

public class InstantiationFailedException extends RuntimeException {
  public InstantiationFailedException(Throwable cause) {
    super(cause);
  }
}
